services:
  env:
    build: ./docker
    volumes:
      - ./:/code
    working_dir: /code
    tty: true
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --port 8888 --allow-root --no-browser
